export * from './common';
export * from './icons';
export { Header } from './header/header.component';
export { Footer } from './footer/footer.component';
export { HeaderTop } from './header/header-top.comonent';
export { HeaderToggleMenu } from './header/header-toggle-menu.component';
export { About } from './about/about.component';
export { ContactUs } from './contact-us/contact-us.component';
export { Policy } from './policy/policy.component';
export { Services } from './servceis/services.component';
export { Home } from './home/home.component';
